[package]
name = "garage_control"
version = "0.1.0"
authors = ["pi"]
edition = "2018"

[dependencies]
rppal = "0.8"
actix = "0.7.9"
actix-web = "0.7.16"
serde_json = "1.0.33"
serde_derive = "1.0.82"
env_logger = "0.6.0"
